version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - deploy:
          name: Build and push Docker image
          command: |
            docker build -t brenopolanski/demo-saiku-community-website .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push brenopolanski/demo-saiku-community-website
